revault/revault-gui

- Cargo.lock
- Cargo.toml
- README.md
- src/main.rs
- src/revaultd/client/mod.rs
- src/revaultd/mod.rs
- src/ui/state/charging.rs
> refac(log): use tracing

- src/revaultd/mod.rs
- src/revaultd/model.rs
- src/ui/state/cmd.rs
Make revault-gui compat with revaultd f233e2adf2a89d1e17e27e2fae5d4bdcab336fd9
close #26
> fix(revaultd): VaultTransactions

- src/revaultd/mod.rs
> Display revaultd stderr on connection error

- Cargo.lock
- Cargo.toml
- src/revaultd/mod.rs
- src/revaultd/model.rs
- src/ui/app.rs
- src/ui/menu.rs
- src/ui/message.rs
- src/ui/state/cmd.rs
- src/ui/state/deposit.rs
- src/ui/state/mod.rs
- src/ui/view/deposit.rs
- src/ui/view/mod.rs
- src/ui/view/sidebar.rs
> ui: add deposit panel

- src/revaultd/mod.rs
When starting revaultd from the GUI, notify the user if after 10 seconds
the child process still hasn't terminated - it means that revaultd was
started with daemon=false in the conf
Closes #40
> Notify users if they have daemon=false in the conf

- src/ui/message.rs
- src/ui/state/cmd.rs
- src/ui/state/history.rs
- src/ui/state/manager.rs
- src/ui/state/mod.rs
- src/ui/state/stakeholder.rs
- src/ui/state/vault.rs
- src/ui/view/vault.rs
a simpler way for us now and It should help me on some issues
> fix(ui): load txs only if vault is selected

- src/ui/message.rs
- src/ui/state/history.rs
- src/ui/state/manager.rs
- src/ui/state/vault.rs
- src/ui/view/vault.rs
Vault has its own state which will enable
future usage like having different information
sections and actions.
> feat(ui): refac vault state and vault modal view

- Cargo.lock
- Cargo.toml
> Remove tokio from iced features

- src/ui/view/home.rs
- src/ui/view/manager.rs
- src/ui/view/network.rs
- src/ui/view/sidebar.rs
- src/ui/view/vault.rs
> Refactor: use to_string() instead of format!

- src/revaultd/mod.rs
- src/revaultd/model.rs
- src/ui/app.rs
- src/ui/component/button.rs
- src/ui/message.rs
- src/ui/state/cmd.rs
- src/ui/state/manager.rs
- src/ui/view/history.rs
- src/ui/view/manager.rs
- src/ui/view/mod.rs
> ui: refac manager send

- src/revaultd/mod.rs
- src/revaultd/model.rs
- src/ui/app.rs
- src/ui/component/mod.rs
- src/ui/message.rs
- src/ui/state/cmd.rs
- src/ui/state/manager.rs
- src/ui/state/mod.rs
- src/ui/state/sign.rs
- src/ui/state/spend_transaction.rs
- src/ui/view/home.rs
- src/ui/view/manager.rs
- src/ui/view/mod.rs
- src/ui/view/spend_transaction.rs
> UI import spend transaction

- src/revaultd/model.rs
- src/ui/message.rs
- src/ui/state/stakeholder.rs
- src/ui/state/vault.rs
- src/ui/view/mod.rs
- src/ui/view/stakeholder.rs
- src/ui/view/vault.rs
> Refac acknowledge vault section

- src/revaultd/config.rs
- src/ui/view/settings/boxes.rs
> Update the settings 

- src/revaultd/mod.rs
- src/ui/message.rs
- src/ui/state/cmd.rs
- src/ui/state/manager.rs
- src/ui/state/stakeholder.rs
- src/ui/state/vault.rs
- src/ui/view/home.rs
- src/ui/view/vault.rs
based on #58 
waiting cancel feature on revaultd
> ui: list unvaulting vaults and add revault action

- Cargo.lock
- Cargo.toml
- src/ui/app.rs
- src/ui/component/mod.rs
- src/ui/view/deposit.rs
- src/ui/view/history.rs
- src/ui/view/home.rs
- src/ui/view/manager.rs
- src/ui/view/network.rs
- src/ui/view/settings/mod.rs
- src/ui/view/spend_transaction.rs
- src/ui/view/stakeholder.rs
- src/ui/view/vault.rs
:warning: seems we have a problem with the scrollbar
we can wait it to be fixed: https://github.com/hecrj/iced/issues/765
or we can add some padding everywhere it is used
> dep: bump iced version to 0.3.0

- src/revaultd/model.rs
- src/ui/view/vault.rs
* add derivation_index and received_at to vault model
* improve vault detail view
> ui: improve vault detail view

- src/revaultd/model.rs
- src/ui/component/mod.rs
- src/ui/icon.rs
- src/ui/state/manager.rs
- src/ui/state/stakeholder.rs
- src/ui/view/home.rs
based on #65 
close #30 
close #67 
close #70 
close #77
> ui: refac home overview

- README.md
- doc/DEMO.md
Needs https://github.com/revault/revaultd/pull/153
Closes #74
> Add MEMO.md, update README.md accordingly

- src/revaultd/config.rs
- src/ui/view/settings/boxes.rs
- src/ui/view/settings/mod.rs
Need  https://github.com/revault/revaultd/pull/210
> Update revaultd config: add scripts config

- src/ui/app.rs
- src/ui/component/icon.rs
- src/ui/menu.rs
- src/ui/message.rs
- src/ui/state/mod.rs
- src/ui/state/stakeholder.rs
- src/ui/state/vault.rs
- src/ui/view/home.rs
- src/ui/view/mod.rs
- src/ui/view/sidebar.rs
- src/ui/view/stakeholder.rs
- src/ui/view/vault.rs
Stakeholder deposit become Create Vault.
last commit:
> refac vault acknowledge for vault creation

- .gitignore
- src/app/menu.rs
- src/app/message.rs
- src/app/mod.rs
- src/app/state/cmd.rs
- src/app/state/emergency.rs
- src/app/state/mod.rs
- src/app/view/emergency.rs
- src/app/view/mod.rs
- src/app/view/sidebar.rs
- src/revaultd/mod.rs
- src/ui/component/mod.rs
- src/ui/icon.rs
waiting for revaultd emergency method
> ui: add emergency modal

- src/app/view/home.rs
Stakeholder does not have Deposit panel anymore, so CreateVault should be used instead of Deposit
> fix: wrong message in stakeholder view deposit button

- src/app/state/stakeholder.rs
- src/revaultd/model.rs
> fix app vaults list: exclude deposit

- src/app/state/manager.rs
better to not load moved vaults
close #135
> fix: add filter to manager home list vaults

- src/app/mod.rs
- src/app/state/cmd.rs
- src/app/state/deposit.rs
- src/app/state/emergency.rs
- src/app/state/manager.rs
- src/app/state/spend_transaction.rs
- src/app/state/stakeholder.rs
- src/app/state/vault.rs
- src/app/state/vaults.rs
- src/app/view/home.rs
- src/app/view/manager.rs
- src/app/view/settings/boxes.rs
- src/app/view/sign.rs
- src/app/view/stakeholder.rs
- src/app/view/vault.rs
- src/app/view/vaults.rs
- src/main.rs
- src/ui/component/button.rs
- src/ui/component/image.rs
- src/ui/component/mod.rs
Closes #142
This PR doesn't solve every warning, but it's already a great improvement :)
> Solve clippy warnings

- src/app/state/manager.rs
- src/app/view/manager.rs
> ui: Display a warning if spend creation failed

- src/app/state/manager.rs
- src/app/view/manager.rs
- src/ui/component/form.rs
- src/ui/component/mod.rs
- src/ui/icon.rs
Introduce a new ui component: `form`
Refac the manager send output selection with it
close #140
> UI add form component

- src/app/state/manager.rs
- src/app/state/spend_transaction.rs
- src/app/view/manager.rs
- src/app/view/spend_transaction.rs
- src/revaultd/model.rs
To be tested with https://github.com/revault/revaultd/pull/218
> Display real spend amount, without considering change and cpfp

- src/app/view/home.rs
> Improve manager home balance ui

- src/app/state/manager.rs
- src/app/view/manager.rs
- src/ui/component/mod.rs
The final step of the send process redirects
now to the created spend transaction.
close #90
> Redirects user after spend tx creation

- src/app/state/manager.rs
- src/app/state/spend_transaction.rs
- src/app/view/manager.rs
- src/app/view/spend_transaction.rs
- src/ui/icon.rs
> refac ui: spend transaction detail

- src/app/message.rs
- src/app/mod.rs
- src/app/state/charging.rs
- src/app/view/mod.rs
- src/app/view/spend_transaction.rs
- src/revaultd/mod.rs
based on #162 
It does not modify totally the spend transaction view yet
> Add managers threshold to app context

- src/app/state/vault.rs
The command revocationtx or unvaulttx were called
multiple time because the state did not know if
the command was already sent and start it after
a signer message.
before:
```
Aug 11 11:04:03.576  INFO request: revault_gui::revaultd: method="getrevocationtxs"
Aug 11 11:04:59.191  INFO request: revault_gui::revaultd: method="revocationtxs"
Aug 11 11:04:59.204  INFO request: revault_gui::revaultd: method="revocationtxs"
Aug 11 11:04:59.206  INFO request: revault_gui::revaultd: method="revocationtxs"
```
after:
``` 
Aug 11 11:12:34.974  INFO request: revault_gui::revaultd: method="getrevocationtxs"
Aug 11 11:12:39.341  INFO request: revault_gui::revaultd: method="revocationtxs"
```
> fix: add processing lock to secure, delegate vault

- Cargo.lock
- Cargo.toml
- contrib/tools/dummysigner/Cargo.lock
- contrib/tools/dummysigner/Cargo.toml
In order to fix the fontconfig error.
> fix dep: remove default features for iced

- src/installer/mod.rs
> fix installer: decode hex encoded noise key

- src/app/config.rs
- src/installer/mod.rs
- src/main.rs
Add revaultd_path as env var so the user can define by advance the field in the installed gui config
> Add revaultd_path env var to installer

- src/installer/mod.rs
> installer: canonicalize paths

- src/app/message.rs
- src/app/state/cmd.rs
- src/app/state/settings.rs
- src/app/view/settings/boxes.rs
- src/app/view/settings/mod.rs
- src/revaultd/mod.rs
- src/ui/component/badge.rs
Needs https://github.com/revault/revaultd/pull/256
Stakeholder view:
(Sadly watchtowers are always dead 🤷🏻‍♀️)
Manager view:
> Rework settings panel 🎉 

- src/app/view/emergency.rs
- src/app/view/manager.rs
- src/app/view/spend_transaction.rs
- src/app/view/stakeholder.rs
- src/app/view/vault.rs
- src/ui/component/button.rs
- src/ui/icon.rs
> ui: add close_button with icon

- src/app/state/manager.rs
> fix missing empty amount check

- .github/workflows/main.yml
- Cargo.lock
- Cargo.toml
- src/app/state/manager.rs
- src/app/state/sign.rs
- src/app/state/spend_transaction.rs
- src/app/state/stakeholder.rs
- src/app/state/vault.rs
- src/app/state/vaults.rs
- src/hw/mod.rs
- src/hw/specter.rs
> hw: add specter wallet

- README.md
- src/app/config.rs
- src/main.rs
> Add network flag to args

- src/app/state/stakeholder.rs
- src/app/state/vault.rs
After creating a vault the user is redirected
back to home panel if their is no more deposits
close #202
> fix app: close vault creation panel if there is no more deposits

- src/installer/mod.rs
- src/installer/step/mod.rs
- src/installer/view.rs
- src/main.rs
> installer: auto-fill bicoind parameters according to network

- .github/workflows/main.yml
- README.md
> Add dependency list to README

- src/app/mod.rs
- src/app/view/sidebar.rs
> Add deposit panel to stakeholder

- src/app/view/manager.rs
- src/app/view/vault.rs
> fix spending round wording

- src/app/view/deposit.rs
- src/app/view/emergency.rs
- src/app/view/home.rs
- src/app/view/layout.rs
- src/app/view/manager.rs
- src/app/view/settings/boxes.rs
- src/app/view/sidebar.rs
- src/app/view/sign.rs
- src/app/view/spend_transaction.rs
- src/app/view/stakeholder.rs
- src/app/view/vault.rs
- src/app/view/vaults.rs
- src/installer/view.rs
- src/loader.rs
- src/ui/component/button.rs
- src/ui/component/form.rs
- src/ui/component/mod.rs
- src/ui/component/text.rs
change from:
```rust
text::bold(text::small("hello"))
```
```rust
Text::new("hello").bold().small()
```
> Add Text to ui components

- src/app/message.rs
- src/app/state/deposit.rs
- src/app/state/emergency.rs
- src/app/state/vaults.rs
- src/app/view/deposit.rs
- src/app/view/emergency.rs
- src/app/view/mod.rs
- src/app/view/sidebar.rs
- src/app/view/vaults.rs
- src/daemon/client/mod.rs
- src/daemon/model.rs
- tests/app.rs
> Add loading state to States

- src/app/view/home.rs
> Add activating vaults and amount to stk home

- src/installer/step/manager.rs
- src/installer/step/mod.rs
- src/installer/step/stakeholder.rs
> installer: disable cosigners by default

- src/app/view/manager.rs
> fix view for importing a spend tx

- src/installer/step/stakeholder.rs
Needs https://github.com/revault/revaultd/pull/313
> installer: Accept signet addresses for emergency

- src/installer/step/stakeholder.rs
> Check that emergency address is v0 P2WSH

- hwi/src/dummysigner.rs
- hwi/src/lib.rs
- src/app/message.rs
- src/app/mod.rs
- src/app/state/manager.rs
- src/app/state/mod.rs
- src/app/state/sign.rs
- src/app/state/stakeholder.rs
- src/app/state/vault.rs
- src/app/state/vaults.rs
- src/app/view/mod.rs
- src/app/view/stakeholder.rs
- src/app/view/vault.rs
- ui/src/component/badge.rs
> Delegate batching

- src/app/state/emergency.rs
- src/app/view/emergency.rs
- src/app/view/mod.rs
- tests/app.rs
Emergency state changes as triggered
if the status of a vault is a emergency status or
the emergency button was pressed.
close #249
> Add triggered state to emergency

- Cargo.lock
- src/app/menu.rs
- src/app/message.rs
- src/app/mod.rs
- src/app/state/cmd.rs
- src/app/state/history.rs
- src/app/state/manager.rs
- src/app/state/mod.rs
- src/app/state/stakeholder.rs
- src/app/view/history.rs
- src/app/view/home.rs
- src/app/view/mod.rs
- src/app/view/sidebar.rs
- src/app/view/vault.rs
- src/daemon/client/mod.rs
- src/daemon/model.rs
- tests/app.rs
need https://github.com/revault/revaultd/pull/279
It retrieves all the history, no pagination yet
> Gethistory

- .github/workflows/main.yml
https://github.com/rust-lang/rust/issues/90342
> ci: disable nightly build for macOS

- src/app/view/spend_transaction.rs
> fix wording in spend tx broadcast view

- src/app/state/manager.rs
> spend_tx: remove duplicate error for empty values

- src/app/view/stakeholder.rs
> fix wording in stakeholder delegate view

- src/app/state/manager.rs
- src/app/view/manager.rs
- ui/src/component/mod.rs
Sorry I remove the little progress bars which had complexity in the layout.
close #255
> fix spend creation modal layout

- README.md
- src/main.rs
> fix iced application: enforce scale factor

- README.md
- Add fontconfig
- Remove useless Vulkan loader link
> fix required dependency list

- doc/DEMO_TESTNET.md
wait for #225 and a new release to bump
> doc: enhance demo testnet

- Cargo.toml
- hwi/Cargo.toml
- ui/Cargo.toml
Some fields are mandatory for the crates
to be published on crates.io
> fix cargo files: fill mandatory fields

- src/daemon/client/mod.rs
- src/daemon/model.rs
- tests/app.rs
- tests/utils/mock.rs
Mock daemon should handle
request in given order and
be able to return response
whatever the request body.
> Enhance mock daemon client

- hwi/src/dummysigner.rs
- hwi/src/lib.rs
- hwi/src/specter.rs
- src/app/state/manager.rs
- src/app/state/sign.rs
- src/app/view/manager.rs
- src/app/view/warning.rs
Dummysigner user may sign the psbt with another key than his manager key, producing the behavior described in #253
> Check spend tx sigs after hw returned psbt

- src/app/message.rs
- src/app/state/history.rs
- src/app/state/manager.rs
- src/app/state/stakeholder.rs
- src/app/view/history.rs
- src/app/view/mod.rs
- src/daemon/model.rs
- tests/app.rs
- ui/src/icon.rs
> Add event detail history

- src/conversion.rs
> ui: Display amounts with 8 decimals

- src/app/state/manager.rs
- src/app/state/stakeholder.rs
- src/app/view/sidebar.rs
> Refac home loading

- src/app/context.rs
- src/app/message.rs
- src/app/state/cmd.rs
- src/app/state/spend_transaction.rs
- src/app/view/manager.rs
- src/app/view/spend_transaction.rs
- src/daemon/client/mod.rs
- src/daemon/embedded.rs
- src/daemon/mod.rs
> Add spend tx priority

- src/app/menu.rs
- src/app/message.rs
- src/app/mod.rs
- src/app/state/cmd.rs
- src/app/state/manager.rs
- src/app/state/mod.rs
- src/app/state/revault.rs
- src/app/state/stakeholder.rs
- src/app/state/vault.rs
- src/app/state/vaults.rs
- src/app/view/home.rs
- src/app/view/layout.rs
- src/app/view/mod.rs
- src/app/view/revault.rs
- src/app/view/sidebar.rs
- src/app/view/vault.rs
- tests/app.rs
- tests/app_revault.rs
- tests/app_stakeholder.rs
- ui/src/component/badge.rs
- ui/src/icon.rs
> Add revault vaults panel

- src/app/message.rs
- src/app/state/manager.rs
- src/app/state/spend_transaction.rs
- src/app/view/manager.rs
- tests/app_manager.rs
Display unvault output amount instead of
vault amount
close #334
> fix inputs selection for spend tx

- .github/workflows/main.yml
> fix ci: reinstate build and test for macos nightly and beta

- Cargo.lock
- Cargo.toml
- src/installer/view.rs
- ui/Cargo.toml
Button `min_width` method is not fund.
The width is fixed instead.
> bump iced 0.4

- src/app/view/manager.rs
- src/app/view/revault.rs
- src/app/view/vault.rs
- ui/src/component/badge.rs
- ui/src/icon.rs
> fix icon for multiple selection

- Cargo.lock
- src/app/menu.rs
- src/app/message.rs
- src/app/mod.rs
- src/app/state/manager.rs
- src/app/state/mod.rs
- src/app/state/spend_transaction.rs
- src/app/view/history.rs
- src/app/view/home.rs
- src/app/view/manager.rs
- src/app/view/sidebar.rs
- src/app/view/spend_transaction.rs
- src/daemon/model.rs
- tests/app.rs
list the spend transactions
add a button: initiate a spending
add a form to import a spend
> Refac manager send panel

- src/app/state/manager.rs
- tests/app_manager.rs
getunvaultx is only allowed for stakholders
close #355
> fix spend creation: use listpresignedtransactions

- src/app/state/manager.rs
- tests/app_manager.rs
`ManagerImportSendTransactionState` currently stores the psbt directly in `psbt_imported`. This has been updated to `SpendTransaction`. Following this change is a chain of minor changes under `impl State` for the same.
The implemented test only checks if the parsing for a `psbt` string happens through `SpendTransaction::from_psbt_str`. This PR resolves #79
> Changed `Psbt` to `SpendTransaction`.
