Cargo.lock
Cargo.toml
src/main.rs
src/revaultd/client/mod.rs
src/revaultd/mod.rs

__env var:__
`REVAULTGUI_DEBUG` (bool)  is used to specify logger level 
and will be used to enable hecrj/iced debug mode.
__logger:__
Only two log level: debug or default.
example: `REVAULTGUI_DEBUG=true ./revault-gui > log.txt`

feat: add logger setup

---

.github/workflows/main.yml
Cargo.lock
Cargo.toml
src/ui/app.rs
src/ui/component/button.rs
src/ui/icon.rs
src/ui/message.rs
src/ui/view/vault.rs

ClipboardContext is added to ui::App
using https://github.com/alacritty/copypasta
which have clipboard support for
Windows, Mac OSX, GNU/Linux, and FreeBSD.
Support was tested with:
- Xorg    | success
- Wayland | failed

ui: add clipboard to app

---

src/main.rs
src/revault.rs
src/ui/app.rs
src/ui/menu.rs
src/ui/message.rs
src/ui/mod.rs
src/ui/state/charging.rs
src/ui/state/history.rs
src/ui/state/installing.rs
src/ui/state/manager.rs
src/ui/state/mod.rs
src/ui/state/stakeholder.rs
src/ui/view/history.rs
src/ui/view/home.rs
src/ui/view/manager.rs
src/ui/view/mod.rs
src/ui/view/network.rs
src/ui/view/sidebar.rs
src/ui/view/vault.rs

split message module for clarity.
revault is a new module which will stock user role
transaction kinds and revault constants or enums.
Context is moved to the module using it: view.
Menu is moved in its own module in ui tree.

refac(ui): split message module

---

README.md
src/main.rs
src/revaultd/mod.rs
src/ui/app.rs
src/ui/state/charging.rs

Add an environment variable for specifying revaultd path. When revaultd
isn't running, uses this variable to start the binary. If not provided,
the gui will call the `revaultd` command.
Fixes #18

Add a REVAULTD_PATH environment variable

---

src/conversion.rs
src/main.rs
src/ui/app.rs
src/ui/state/manager.rs
src/ui/view/home.rs
src/ui/view/manager.rs
src/ui/view/mod.rs
src/ui/view/stakeholder.rs
src/ui/view/vault.rs

A converter converts a given amount in satoshis
to another amount in a chosen unit.
This struct can be enhanced with currency
conversion.
Converter is shared to each view through the Context,
because it is only a display feature and does not have
core revault logic.
close #32

mod conversion: add converter and unit

---

src/ui/app.rs
src/ui/component/button.rs
src/ui/icon.rs
src/ui/menu.rs
src/ui/message.rs
src/ui/state/cmd.rs
src/ui/state/history.rs
src/ui/state/manager.rs
src/ui/state/mod.rs
src/ui/state/sign.rs
src/ui/state/stakeholder.rs
src/ui/state/vault.rs
src/ui/view/mod.rs
src/ui/view/sidebar.rs
src/ui/view/sign.rs
src/ui/view/stakeholder.rs
src/ui/view/vault.rs

first commit, add a delegate section to vault modal that a stakeholder can click on it and start signing unvault_tx
last commit add the delegate funds panel where the user can:
- see the amount delegated to managers
- see the available acknowledged vaults that can be delegated
- see the vaults delegated to managers

UI add delegate panel

---

src/ui/app.rs
src/ui/view/sidebar.rs

The user can not anymore edit the role in the sidebar
if the revaultd configuration does not specify both
the stakeholder and the manager configuration parts.
close #75
close #71

fix(ui): set edit_role in context view

---

src/ui/view/home.rs

Stakeholde home overview displays a button to delegate funds
and the button was redirecting to acknowledge funds panel
instead of the delegate funds panel.
close #89

fix ui: wrong home delegate-funds button message

---

src/ui/state/vault.rs

The previous warning message must be unset before
a new command started or after a command succeed.
close #93

fix ui vault state: unset warning message

---

src/revaultd/model.rs
src/ui/app.rs
src/ui/component/icon.rs
src/ui/menu.rs
src/ui/message.rs
src/ui/state/mod.rs
src/ui/state/stakeholder.rs
src/ui/state/vaults.rs
src/ui/view/mod.rs
src/ui/view/sidebar.rs
src/ui/view/stakeholder.rs
src/ui/view/vault.rs
src/ui/view/vaults.rs

History panel was not a time lined list of the wallet transactions, it was only a list of current and passed vaults.
For clarity the panel is renamed for Vaults
Vaults panel now has filter on the status, The filters are:
* current: all vaults with status different of Cancelled and Spent
* Not Delegated: all vaults with status: funded, securing, secured, activating
* Delegated: all vaults with status: active
* Moving: all vaults with status: unvaulting, unvaulted, spending, cancelling
* Passed or Moved: all vaults with status Cancelled and Spent
close #104

UI: refac history for vaults detail

---

src/ui/component/badge.rs
src/ui/component/icon.rs
src/ui/component/mod.rs
src/ui/state/stakeholder.rs
src/ui/view/stakeholder.rs
src/ui/view/vault.rs

The panel is simplified:
The filters are removed and only
available funds for delegation are displayed.

refac ui: delegate funds panel

---

README.md
contrib/revault_gui.toml
doc/DEMO.md
src/main.rs
src/revaultd/config.rs
src/ui/app.rs
src/ui/config.rs
src/ui/mod.rs
src/ui/state/charging.rs
src/ui/view/charging.rs

Remove env var for a config file passed with `--conf` flag
revaultd_config_path is not optional in the config

Use a config file to store ui config

---

src/app/message.rs
src/app/state/manager.rs
src/app/view/manager.rs
src/ui/color.rs
src/ui/component/mod.rs
src/ui/icon.rs

This PR is a first improvement to the spend flow. There are still smaller TODOs that will be covered in the next PRs.
Add recipients:
Select fee:
~~"Please enter valid amount" warning is triggered when the amount can't fit in a u32. Perhaps I should avoid using another card and writing "Please enter a valid amount" directly in the "Continue" button? Open for discussion :)~~
The fee is stored as an unsigned integer, and the user can't enter non-digit characters 
Select coins:
Sign:

Improve spend flow

---

src/app/state/cmd.rs
src/app/state/emergency.rs
src/app/state/manager.rs
src/app/state/spend_transaction.rs
src/app/state/stakeholder.rs
src/app/state/vaults.rs
src/revaultd/mod.rs

Retrieve the vaults with a list of outpoints.
This fix the need to retrieve all vaults and filter
them by selected outpoints in the spend_transaction panel.

add revaultd::get_vaults

---

Cargo.lock
Cargo.toml
README.md
src/app/config.rs
src/app/mod.rs
src/installer/message.rs
src/installer/mod.rs
src/installer/step/common.rs
src/installer/step/manager.rs
src/installer/step/mod.rs
src/installer/step/stakeholder.rs
src/installer/view.rs
src/main.rs
src/revault.rs
src/revaultd/config.rs
src/revaultd/mod.rs
src/ui/component/button.rs
src/ui/component/form.rs

Add installer
Different use case:
1. --conf is present, the app tries to run and returns error if failure.
2. --datadir is present, the app tries to run and starts installer if config is
not fund in datadir or datadir does not exist.
3. no flags, the app tries to run with default datadir path, starts installer 
if config is not fund in default datadir or default datadir does not exist.
close #106

Feat installer

---

src/app/view/vault.rs

Vaults can have same Address or deposit txid.
Vault outpoint is the vault id.
close #91

fix view: list vaults with outpoints

---

src/app/state/manager.rs
src/app/state/stakeholder.rs

After a vault is selected and updated the home panel
must be refreshed in order to display the new state.
close #148

fix home panel: reload models after unselect vault

---

src/app/state/spend_transaction.rs

* Add a processing lock in order to not spam updatespendtx
* Remove wrong outpoint check in the collection of
derivation indexes. It was a wrong == between a deposit
outpoint and an unvault outpoint (psbt.input.previous_output)

fix app: state spend_transaction sign

---

src/app/state/manager.rs
src/app/view/manager.rs

This a temporary fix to show an error message when
two recipients addresses are the same and prevent
user to go next step. Because the recipients outputs
are stored in a address-amount map, a recipient output
with the same address than an other replace it.
In order to change this, revaultd needs to accept a
vector of (address, amount) tuple instead of a map.
refers to  #130

fix spend: check duplicate recipients addresses

---

Cargo.lock

compilation was broken on nightly:
https://github.com/rust-num/num-bigint/issues/218
cargo update -p num-bigint

fix dep: bump num-bigint

---

src/app/context.rs
src/app/mod.rs
src/app/state/cmd.rs
src/app/state/deposit.rs
src/app/state/emergency.rs
src/app/state/manager.rs
src/app/state/mod.rs
src/app/state/settings.rs
src/app/state/sign.rs
src/app/state/spend_transaction.rs
src/app/state/stakeholder.rs
src/app/state/vault.rs
src/app/state/vaults.rs
src/app/view/deposit.rs
src/app/view/emergency.rs
src/app/view/home.rs
src/app/view/manager.rs
src/app/view/settings/mod.rs
src/app/view/sidebar.rs
src/app/view/sign.rs
src/app/view/spend_transaction.rs
src/app/view/stakeholder.rs
src/app/view/vault.rs
src/app/view/vaults.rs
src/daemon/client/jsonrpc.rs
src/daemon/client/mod.rs
src/loader.rs
src/main.rs

Add a generic trait `daemon::Client`
The PR is quite verbose because we want the trait as generic compiled at build time and not `dyn` in a `Box`

refac: add generic trait to revaultd client

---

Cargo.lock
Cargo.toml
src/app/mod.rs
src/app/state/deposit.rs
src/daemon/client/mod.rs
src/daemon/model.rs
src/lib.rs
src/main.rs
tests/app.rs
tests/utils/mock.rs
tests/utils/mod.rs
tests/utils/sandbox.rs

based on #229 
now, we can simulate iced runtime for State trait with a simple recursion:
https://github.com/revault/revault-gui/pull/231/files#diff-7522a221ae2213d1626bedc98e42c0a74e686b5415bcede478b53fcd29d9d521R27
and thanks to the daemon::Client trait as generic, we have a simple mock::DaemonClient
https://github.com/revault/revault-gui/pull/231/files#diff-7a3ad6290169e7ae5cb266c5b2b3dc91645936f0bed1b7d6fdfd0ba1b247b50dR10
and it permits us to mock answers to state commands:
https://github.com/revault/revault-gui/pull/231/files#diff-e12e015dc6f52c7159e903d60306c405f5cc3358a30108d7eb7c8a1ae8c22c97R30
and then test the state: for example DepositState load the deposit bitcoin address
https://github.com/revault/revault-gui/pull/231/files#diff-e12e015dc6f52c7159e903d60306c405f5cc3358a30108d …

Add tests directory

---

src/app/view/spend_transaction.rs
src/app/view/vault.rs

remove the transaparent green button broadcasted

fix success message after a tx broadcast

---

src/main.rs

Mio logs are quite annoying:
```
[1639730512][mio::poll][TRACE] reregistering event source with poller: token=Token(16), interests=READABLE | WRITABLE
[1639730512][mio::poll][TRACE] reregistering event source with poller: token=Token(16), interests=READABLE | WRITABLE
...
```

fix log: set level off for mio

---

.github/workflows/main.yml

ci build failed for ubuntu-latest because
libudev-dev_245.4-4ubuntu3.13_amd64.deb
does not exist on azure.archive.ubuntu.com
Tried to use 245.4-4ubuntu3.14 but
apt-get install did not found it.
Version is downgraded to 245.4-4ubuntu3
for libudev1 (required dep of libudev-dev)
and libudev-dev

fix CI ubuntu-latest: pin libudev-dev version

---

src/app/context.rs
src/app/message.rs
src/app/mod.rs
src/app/state/cmd.rs
src/app/state/manager.rs
src/app/state/settings.rs
src/app/state/stakeholder.rs
src/app/view/settings/mod.rs
src/main.rs
tests/app.rs

App has a running subscription
to check blockheight every 30s
and store it in its context.
Views will retrieve blockheight
directly from context.
It makes less information to load for states, related to #46

Move blockheight in app context.

---

src/installer/step/mod.rs
src/installer/view.rs

The input of `PrivateNoiseKey` present [here](https://github.com/revault/revault-gui/blob/master/src/installer/view.rs#L217) currently is only constraining the input to 64 bytes, but doesn't check if the string is a valid hex sequence.
Based on the implementation of the validation for `noise_key` for `DefineCoordinator` present [here](https://github.com/revault/revault-gui/blob/master/src/installer/step/mod.rs#L315) the validation for hex sequence have been made as requested in #348

Hex validation for `PrivateNoiseKey`.

---

src/installer/step/mod.rs

Currently, the `Installer` gives a warning:
```
Invalid format for a socket address
```
If the entered host address at "Coordinator information" does not contain the port. Since there exists a default port that must be used if not provided, the GUI must try using it.
The issue was raised in #250 and this PR closes it.

Adding default port value if not provided.
